version: '3.8'

services:
  app:
    build: .
    container_name: nest-app
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo-data:
